# Generated by Django 5.0 on 2023-12-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_miles_car_kms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='features',
        ),
    ]
