# Generated by Django 5.0 on 2023-12-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Air_Conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='Airbags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='Alarm_System',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='Audio_Interface',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='Auto_Start_Stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='Cruise_Control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='Direct_Fuel_Injection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='ParkAssist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='Power_Steering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='Reversing_Camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='Seat_Heating',
            field=models.BooleanField(default=False),
        ),
    ]
